# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BenHall.ca
#email: your-email@domain.com
description: Ben Hall is a software engineer and technical director at Intelliware with expertise in Java and agile development methods. He might also write about goju-ryu karate, sailing, and life with 3 kids.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://benhall.ca" # the base hostname & protocol for your site
twitter_username: BenHall
github_username:  hallb
permalink: pretty

# Build settings
markdown: kramdown
