# Basic site configuration
baseURL = "https://benhall.ca/"
languageCode = "en-us"
title = "BenHall.ca"
theme = "stack"

# Enable basic features
enableRobotsTXT = true
enableEmoji = true

# Output formats
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "JSON"]
section = ["HTML", "RSS", "JSON"]
taxonomy = ["HTML", "RSS", "JSON"]
taxonomyTerm = ["HTML", "RSS", "JSON"]

# Default language
defaultContentLanguage = "en"

# Configure taxonomies
[taxonomies]
tag = "tags"
category = "categories"

# Configure menu
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
params = { icon = "home" }

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2
params = { icon = "user" }

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 3
params = { icon = "search" }

# Basic theme settings
[params]
mainSections = ["post"]
favicon = "/favicon.ico"

[params.sidebar]
subtitle = "Software, karate, kids, sailing, and cooking"

[params.sidebar.bio]
enabled = true
content = "Software engineer and technical director at Intelliware with expertise in Java and agile development methods."

[params.widgets]
homepage = [
    {type = "search", params = {placeholder = "Search..."}},
    {type = "archives"},
    {type = "tag-cloud"}
]
page = [
    {type = "search", params = {placeholder = "Search..."}},
    {type = "toc"}
]

# Social media links
[[params.socialIcons]]
name = "github"
url = "https://github.com/hallb"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/BenHall"

# The following settings are commented out as they are either default values or optional features
# Uncomment and modify as needed

# [imaging]
# anchor = "Smart"
# quality = 75
# resampleFilter = "Lanczos"

# [params.footer]
# since = 2013

# [params.dateFormat]
# published = "Jan 02, 2006"
# lastUpdated = "Jan 02, 2006 15:04 MST"

# [params.sidebar.avatar]
# enabled = true
# local = true
# src = "img/avatar.png"

# [params.article]
# math = false
# toc = true
# readingTime = true

# [params.article.license]
# enabled = false

# [params.comments]
# enabled = false

# [params.opengraph.twitter]
# card = "summary_large_image"
# site = "@BenHall"

# [params.defaultImage.opengraph]
# enabled = false
# local = false

# [markup.goldmark.renderer]
# unsafe = true

# [markup.tableOfContents]
# endLevel = 4
# ordered = true
# startLevel = 2

# [markup.highlight]
# noClasses = false
# codeFences = true
# guessSyntax = true
# lineNoStart = 1
# lineNos = true
# lineNumbersInTable = true
# tabWidth = 4

# [params.article.type]
# Post = "post"
# Page = "page" 